### ISSUE TITLE
Google fonts

### ISSUE THREAD

**Issue by shmuelbarkin** [shmuelbarkin/gf-custom-styling#4]
**Tasks**
- [x] When I update the Google font it does not work. I am getting this error in Chrome 
```
Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://fonts.google.com/specimen/Felipa".
(index):113
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://fonts.google.com/specimen/Felipa with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

**Other**
- [x] We need to insure that this will work with font names that are more than one word such "Noto Sans"

**Error Environment**
- URL for testing: https://thissiteworks.com/wp/styles/
- Browser: Chrome
- OS: macOS

**Comment by pacikav** [comment]
was not able reproduce this issue
it seems url you've pasted was wrong
I see it looks like `https://fonts.googleapis.com/css?family=Felipa`

**Comment by shmuelbarkin** [comment]
@pacikav you are right, I was using the wrong URL, I have tested with the correct URL and it works for a fonts with a single word name or multiple word name.
