### ISSUE TITLE
Google fonts settings 

### ISSUE THREAD

**Issue by shmuelbarkin** [shmuelbarkin/gf-custom-styling#5]
**Task**
- [x] Construct the `Font family url:` from the `Font family name:` this way the user would only need to input the `Font family name:` in the settings. This would enable use to remove the `Font family url:` setting and simplify this setting for users. It will also prevent a mismatch between the above two settings. 

*Example 1*
1. User inputs `Noto Sans`
2. We construct the URL like so `https://fonts.googleapis.com/css?family=Noto+Sans`

*Example 2*
1. User inputs `Roboto`
2. We construct the URL like so `https://fonts.googleapis.com/css?family=Roboto`

**Comment by pacikav** [comment]
please take a look

**Comment by shmuelbarkin** [comment]
@pacikav perfect
