### ISSUE TITLE
Submit button on hover color

### ISSUE THREAD

**Issue by shmuelbarkin** [shmuelbarkin/gf-custom-styling#6]
**Task**
- [x] The submit button on hover has a background of white, the background should be the same color as the primary color set in the plugin settings.

**Error Environment**
* URL for testing: https://thissiteworks.com/wp/styles/
* Browser: Chrome
* OS: macOS

**Comment by pacikav** [comment]
`the background should be the same color as the primary color set in the plugin settings.` -  you mean hove color should be the same as in settings?

**Comment by shmuelbarkin** [comment]
@pacikav correct, but I tested this again now and it is working as intended (maybe it was a caching issue). So I will be closing this issue.
